version: '3.3'
services:
  # HADOOP HDFS STUFF
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - conf/bigdata.env
    ports:
      - 50070:50070
    healthcheck:
      interval: 20s
      retries: 100
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    depends_on:
      - namenode
    healthcheck:
      interval: 20s
      retries: 100
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - conf/bigdata.env
    ports:
      - 50075:50075

  # YARN STUFF
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
    healthcheck:
      interval: 20s
      retries: 100
    links:
      - "namenode"
    ports:
      - 8188:8188
      #- "58188:8188"
    env_file:
      - conf/bigdata.env
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    ports:
      - 8088:8088
      #- "58088:8088"
    depends_on:
      - namenode
      - datanode
    env_file:
      - conf/bigdata.env

  # SPARK STUFF
  spark-master:
    image: bde2020/spark-master:2.2.0-hadoop2.7
      #2.1.1-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
      - 4040:4040
    depends_on:
      - namenode
      - datanode
    healthcheck:
      interval: 20s
      retries: 100
    env_file:
      - conf/bigdata.env
    volumes:
      - ./conf/spark/master.conf:/spark/conf/spark-defaults.conf
  spark-worker:
    image: bde2020/spark-worker:2.2.0-hadoop2.7
    depends_on:
      - spark-master
    healthcheck:
      interval: 20s
      retries: 100
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - conf/bigdata.env
    volumes:
      - ./conf/spark/worker.conf:/spark/conf/spark-defaults.conf
  spark-notebook:
    image: quay.io/comp-bio-aging/notebook:latest
    container_name: spark-notebook
    env_file:
      - conf/bigdata.env
    ports:
      #- 9001:9001
      - 9000:9000
    volumes:
      - ./notebooks:/opt/spark-notebook/notebooks
      - ./conf/notebook/repos/m2:/root/.m2/repository
    depends_on:
      - spark-master
      - namenode

  # HIVE STUFF
  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-server
    env_file:
      - conf/bigdata.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - 10000:10000
  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - conf/bigdata.env
    command: /opt/hive/bin/hive --service metastore
    ports:
      - 9083:9083
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    ports:
      - 5432:5432

  # HUE STUFF
  hue:
    image: gethue/hue:latest
    depends_on:
      - namenode
      - datanode
    ports:
      - 8888:8888
    volumes:
      - ./conf/hue/hue.ini:/hue/desktop/conf/pseudo-distributed.ini