version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    networks:
      - core
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - conf/bigdata.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 50070:50070
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    networks:
      - core
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - conf/bigdata.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  datanode:
  namenode:

networks:
  core:
    external: true
