version: '3'
services:
  spark-master:
    image: bde2020/spark-master:2.2.0-hadoop2.7
    networks:
      - core
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - conf/bigdata.env
  spark-worker:
    image: bde2020/spark-worker:2.2.0-hadoop2.7
    networks:
      - core
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    env_file:
      - conf/bigdata.env
  spark-notebook:
    image: quay.io/comp-bio-aging/notebook:latest
    env_file:
      - conf/bigdata.env
    ports:
      #- 9001:9001
      - 9000:9000
    volumes:
      - ./notebooks:/opt/spark-notebook/notebooks
      - ./conf/notebook/repos/m2/repository:/root/.m2/repository
    depends_on:
      - spark-master
      - namenode
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
  # HUE STUFF
  hue:
    image: gethue/hue:latest
    depends_on:
      - namenode
      - datanode
    ports:
      - 8888:8888
    volumes:
      - ./conf/hue/hue.ini:/hue/desktop/conf/pseudo-distributed.ini
    deploy:
        replicas: 1
        mode: replicated
        restart_policy:
          condition: on-failure

networks:
  core:
    external: true
